# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='np_score',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='party',
            field=models.CharField(default=' ', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='state_code',
            field=models.CharField(default='  ', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=1),
        ),
    ]
