# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160522_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='house_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='house_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rank_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='senate_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='senate_start',
            field=models.IntegerField(default=0),
        ),
    ]
